apiVersion: v2
name: oauth2-proxy
description: Wrapper Helm chart for oauth2-proxy — Google OAuth2 ForwardAuth backend for Traefik on k3s
type: application
version: 0.1.0
appVersion: "v7.6.0"
keywords:
  - oauth2
  - authentication
  - google
  - traefik
  - forwardauth
sources:
  - https://github.com/oauth2-proxy/oauth2-proxy
maintainers:
  - name: frodoagu
dependencies:
  - name: oauth2-proxy
    version: "7.7.1"
    repository: https://oauth2-proxy.github.io/manifests
