---
# ArgoCD Application – nginx serving a single-page application (SPA).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agu-spa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:frodoagu/home.git
    targetRevision: HEAD
    path: charts/agu-spa
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: agu-spa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
