---
# ArgoCD Application – Cloudflare dynamic-DNS updater.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-ddns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:frodoagu/home.git
    targetRevision: HEAD
    path: charts/cloudflare-ddns
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-ddns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
