{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}-base-config
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  configuration.yaml: |
    http:
      use_x_forwarded_for: true
      trusted_proxies:
      - 10.0.0.0/8
    homeassistant:
      name: Home
{{- if .Values.externalUrl }}
      external_url: {{ .Values.externalUrl }}
{{- end }}

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
{{- end }}
