apiVersion: v2
name: argocd
description: Wrapper Helm chart for Argo CD on k3s
type: application
version: 0.1.0
appVersion: "3.4.4"
keywords:
  - argocd
  - gitops
  - continuous-delivery
sources:
  - https://github.com/argoproj/argo-helm
maintainers:
  - name: frodoagu
dependencies:
  - name: argo-cd
    version: "9.7.0"
    repository: https://argoproj.github.io/argo-helm
